version: 2

models:
  - name: dim_customers
    columns:
      - name: customer_id
        tests: [not_null, unique]

  - name: dim_products
    columns:
      - name: product_id
        tests: [not_null, unique]

  - name: dim_employees
    columns:
      - name: employee_id
        tests: [not_null, unique]

  - name: dim_shippers
    columns:
      - name: shipper_id
        tests: [not_null, unique]

  - name: fact_sales
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns: [order_id, product_id]
    columns:
      - name: order_id
        tests:
          - relationships:
              to: ref('stg_orders')
              field: order_id
      - name: product_id
        tests:
          - relationships:
              to: ref('stg_products')
              field: product_id
      - name: customer_id
        tests:
          - relationships:
              to: ref('stg_customers')
              field: customer_id